### ISSUE TITLE
Fix direction of relations in statement table and blackboard display

### ISSUE THREAD

**Issue by mbrush** [NCATS-Tangerine/tkbio#63]
**Statement tables:** S and O often wrong for a  given triple in the statement table (but arrow will sometimes be in the correct direction if added to graph). e.g. below, vemurafenib should be in the subject column for 'drug used for treatment' statements, but instead are in the object column.  

![image](https://user-images.githubusercontent.com/5184212/30607004-812a5686-9d28-11e7-8096-82c6719c20f0.png)

----

**Blackboard arrows:**   Direction of arrows on relations between concepts on the 'blackboard often appear in the wrong direction. e.g. both arrows are wrong in the example below.

![image](https://user-images.githubusercontent.com/5184212/30607140-de89f250-9d28-11e7-84a1-8df041e5034c.png)

**Comment by RichardBruskiewich** [comment]
I found the bug in the concept map arrow direction. This will be fixed in a future production deployment of the code.  On the issue of the statement table direction of S and O, we'll have to more directly check the output from the beacons, which may in some cases, be in error (not sure yet, but will investigate).

**Comment by RichardBruskiewich** [comment]
Actually, for your **vemurafenib** example above, is is likely that the interpretation of the predicate is ambiguous. The database curators interpret the given predicate "drug used for treatment" here as saying that "the drug used for treatment (of the subject) is", rather than "is the drug used for treatment of".  What we probably need to do is enforce the ontology of predicates in such a manner as their application in every knowledge source is consistent.  How we achieve this may be a subject for further NCATS team discussion.  One help may be that we need to have the knowledge sources publish their list of predicates with precise definitions and indications for interpretation. The next Translator  Knowledge Beacon API release may need to add this?

Incidentally, the concept map edge "bug" probably "corrects" the predicate in the manner you have interpreted, but in fact, the concept "bug" fixed will reverse this!

**Comment by RichardBruskiewich** [comment]
I decided to deploy the bug fix to production (http://tkbio.ncats.io) for a small progress victory tonight (and a chance to resolve an issue!).

as for the **vemurafenib** example, I think all such cases will be beacon data curation and predicate semantics ambiguity, not a software bug, thus I resolve this issue. Hopefully, the predicate semantics issue will be taken up elsewhere (see also https://github.com/NCATS-Tangerine/translator-knowledge-beacon/issues/26 and https://github.com/NCATS-Tangerine/beacon-aggregator/issues/21)
